apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kevinc-app-tls
spec:
  secretName: kevinc-app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kevinc.app
  dnsNames:
    - kevinc.app
    - www.kevinc.app
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kevinc.app
          - www.kevinc.app